- name: Copycat Action
  # You may pin to the exact commit or the version.
  # uses: andstor/copycat-action@c2b0316e9ab883478a4a7d40a4fcb03d17f281aa
  uses: andstor/copycat-action@v3.2.4
  with:
    # Personal access token
    personal_token: 
    # The source path to the file(s) or folder(s) to copy from
    src_path: 
    # The destination path to copy the file(s) or folder(s) to
    dst_path: # optional
    # The name of the owner of the repository to push to
    dst_owner: 
    # The name of the repository to push to
    dst_repo_name: 
    # The branch name of the source repository
    src_branch: # optional, default is master
    # The branch name of the destination repository
    dst_branch: # optional, default is master
    # Set to true if the dst_path should be emptied before copying
    clean: # optional
    # A glob pattern for filtering file names
    file_filter: # optional
    # A glob pattern for filtering file paths to be included for copying
    filter: # optional
    # A glob pattern for excluding paths
    exclude: # optional
    # Set to true if the source repository you want to copy from is the GitHub Wiki
    src_wiki: # optional
    # Set to true if the destination repository you want to copy from is the GitHub Wiki
    dst_wiki: # optional
    # A custom git commit message.
    commit_message: # optional
    # The GitHub username to associate commits made by this GitHub action
    username: # optional
    # The email used for associating commits made by this GitHub action
    email: # optional